// Structure: { id: 'Q1', text: 'How often...', options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'] }
const questions = [
    // Test 1: Mental Health Assessment
    {
      id: 'Q1',
      text: 'How often do you have trouble wrapping up the final details of a project, once the challenging parts have been done?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q2',
      text: 'How often do you have difficulty getting things in order when you have to do a task that requires organization?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q3',
      text: 'How often do you have problems remembering appointments or obligations?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q4',
      text: 'When you have a task that requires a lot of thought, how often do you avoid or delay getting started?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q5',
      text: 'How often do you fidget or squirm with your hands or feet when you have to sit down for a long time?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q6',
      text: 'How often do you feel overly active and compelled to do things, like you were driven by a motor?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q7',
      text: 'How often do you make careless mistakes when you have to work on a boring or difficult project?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q8',
      text: 'How often do you have difficulty keeping your attention when you are doing boring or repetitive work?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q9',
      text: 'How often do you have difficulty concentrating on what people say to you, even when they are speaking to you directly?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q10',
      text: 'How often do you misplace or have difficulty finding things at home or at work?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q11',
      text: 'How often are you distracted by activity or noise around you?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q12',
      text: 'How often do you leave your seat in meetings or other situations in which you are expected to remain seated?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q13',
      text: 'How often do you feel restless or fidgety?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q14',
      text: 'How often do you have difficulty unwinding and relaxing when you have time to yourself?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q15',
      text: 'How often do you find yourself talking too much when you are in social situations?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q16',
      text: 'When you’re in a conversation, how often do you find yourself finishing the sentences of the people you are talking to, before they can finish them themselves?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q17',
      text: 'How often do you have difficulty waiting your turn in situations when turn taking is required?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q18',
      text: 'How often do you interrupt others when they are busy?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
    id: 'Q19',
    text: 'Little interest or pleasure in doing things?',
    options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
    section: 'Test1',
    },
    {
      id: 'Q20',
      text: 'Feeling down, depressed, or hopeless?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q21',
      text: 'Feeling more irritated, grouchy, or angry than usual?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q22',
      text: 'Sleeping less than usual, but still have a lot of energy?',
        options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q23',
      text: 'Starting lots more projects than usual or doing more risky things than usual?',
        options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q24',
      text: 'Feeling nervous, anxious, frightened, worried, or on edge?',
        options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q25',
      text: 'Feeling panic or being frightened?',
        options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q26',
      text: 'Avoiding situations that make you anxious?',
        options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q27',
      text: 'Unexplained aches and pains (e.g., head, back, joints, abdomen, legs)?',
        options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q28',
      text: 'Feeling that your illnesses are not being taken seriously enough?',
        options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q29',
      text: 'Thoughts of actually hurting yourself?',
        options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q30',
      text: 'Hearing things other people couldn’t hear, such as voices even when no one was around?',
        options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q31',
      text: 'Feeling that someone could hear your thoughts, or that you could hear what another person was thinking?',
        options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q32',
      text: 'Feeling detached or distant from yourself, your body, your physical surroundings, or your memories?',
        options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q33',
      text: 'Drinking at least 4 drinks of any kind of alcohol in a single day?',
        options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q34',
      text: 'Smoking any cigarettes, a cigar, or pipe, or using snuff or chewing tobacco?',
        options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q35',
      text: 'Using any of the following medicines ON YOUR OWN, that is, without a doctor’s prescription, in greater amounts or longer than prescribed [e.g., painkillers (like Vicodin), stimulants (like Ritalin or Adderall), sedatives or tranquilizers (like sleeping pills or Valium), or drugs like marijuana, cocaine or crack, club drugs (like ecstasy), hallucinogens (like LSD), heroin, inhalants or solvents (like glue), or methamphetamine (like speed)]?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q36',
      text: 'Not knowing who you really are or what you want out of life?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q37',
      text: 'Not feeling close to other people or enjoying your relationships with them?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q38',
      text: 'Problems with sleep that affected your sleep quality over all?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q39',
      text: 'Problems with memory (e.g., learning new information) or with location (e.g., finding your way home)?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q40',
      text: 'Unpleasant thoughts, urges, or images that repeatedly enter your mind?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    {
      id: 'Q41',
      text: 'Feeling driven to perform certain behaviors or mental acts over and over again?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test1',
    },
    // Test 2: ADHD/ADD
    // During the past TWO (2) WEEKS, how much (or how often) have you been bothered by the following problems?
  
    {
      id: 'Q0',
      text: 'Have you ever been diagnosed with ADHD (attention deficit hyperactivity disorder) or ADD (attention deficit disorder) by a licensed medical professional? If you have been diagnosed with both, please report the latest one.',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q1',
      text: 'How often do you have trouble wrapping up the final details of a project, once the challenging parts have been done?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q2',
      text: 'How often do you have difficulty getting things in order when you have to do a task that requires organization?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q3',
      text: 'How often do you have problems remembering appointments or obligations?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q4',
      text: 'When you have a task that requires a lot of thought, how often do you avoid or delay getting started?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q5',
      text: 'How often do you fidget or squirm with your hands or feet when you have to sit down for a long time?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q6',
      text: 'How often do you feel overly active and compelled to do things, like you were driven by a motor?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q7',
      text: 'How often do you make careless mistakes when you have to work on a boring or difficult project?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q8',
      text: 'How often do you have difficulty keeping your attention when you are doing boring or repetitive work?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q9',
      text: 'How often do you have difficulty concentrating on what people say to you, even when they are speaking to you directly?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q10',
      text: 'How often do you misplace or have difficulty finding things at home or at work?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q11',
      text: 'How often are you distracted by activity or noise around you?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q12',
      text: 'How often do you leave your seat in meetings or other situations in which you are expected to remain seated?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q13',
      text: 'How often do you feel restless or fidgety?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q14',
      text: 'How often do you have difficulty unwinding and relaxing when you have time to yourself?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q15',
      text: 'How often do you find yourself talking too much when you are in social situations?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q16',
      text: 'When you’re in a conversation, how often do you find yourself finishing the sentences of the people you are talking to, before they can finish them themselves?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q17',
      text: 'How often do you have difficulty waiting your turn in situations when turn taking is required?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
    {
      id: 'Q18',
      text: 'How often do you interrupt others when they are busy?',
      options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
      section: 'Test2',
    },
  
    // Test 3: Depression
    {
      id: 'QSR1',
      text: 'Falling asleep?',
      options: [
        'I never take longer than 30 minutes to fall asleep.',
        'I take at least 30 minutes to fall asleep, less than half the time.',
        'I take at least 30 minutes to fall asleep, more than half the time.',
        'I take more than 60 minutes to fall asleep, more than half the time.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR2',
      text: 'Sleep during the night?',
      options: [
        'There is no change in my usual appetite.',
        'I eat somewhat less often or lesser amounts of food than usual.',
        'I eat much less than usual and only with personal effort.',
        'I rarely eat within a 24-hour period, and only with extreme personal effort or when others persuade me to eat.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR3',
      text: 'Waking up too early?',
      options: [
        'Most of the time, I awaken no more than 30 minutes before I need to get up.',
        'More than half the time, I awaken more than 30 minutes before I need to get up.',
        'I almost always awaken at least one hour or so before I need to, but I go back to sleep eventually.',
        'I awaken at least one hour before I need to, and can’t go back to sleep.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR4',
      text: 'Sleeping too much?',
      options: [
        'I sleep no longer than 7–8 hours/night, without napping during the day.',
        'I sleep no longer than 10 hours in a 24-hour period including naps.',
        'I sleep no longer than 12 hours in a 24-hour period including naps.',
        'I sleep longer than 12 hours in a 24-hour period including naps.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR5',
      text: 'Feeling sad?',
      options: [
        'I do not feel sad',
        'I feel sad less than half the time.',
        'I feel sad more than half the time.',
        'I feel sad nearly all of the time.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR6',
      text: 'Decreased appetite?',
      options: [
        'There is no change in my usual appetite.',
        'I eat somewhat less often or lesser amounts of food than usual.',
        'I eat much less than usual and only with personal effort.',
        'I rarely eat within a 24-hour period, and only with extreme personal effort or when others persuade me to eat.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR7',
      text: 'Increased appetite?',
      options: [
        'There is no change from my usual appetite.',
        'I feel a need to eat more frequently than usual.',
        'I regularly eat more often and/or greater amounts of food than usual.',
        'I feel driven to overeat both at mealtime and between meals.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR8',
      text: 'Decreased weight (within the last two weeks)?',
      options: [
        'I have not had a change in my weight.',
        'I feel as if I’ve had a slight weight loss.',
        'I have lost 2 pounds or more.',
        'I have lost 5 pounds or more.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR9',
      text: 'Increased weight (within the last two weeks)?',
      options: [
        'I have not had a change in my weight.',
        'I feel as if I’ve had a slight weight gain.',
        'I have gained 2 pounds or more.',
        'I have gained 5 pounds or more.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR10',
      text: 'Concentration/Decision Making?',
      options: [
        'There is no change in my usual capacity to concentrate or make decisions.',
        'I occasionally feel indecisive or find that my attention wanders.',
        'Most of the time, I struggle to focus my attention or to make decisions.',
        'I cannot concentrate well enough to read or cannot make even minor decisions.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR11',
      text: 'View of myself?',
      options: [
        'I see myself as equally worthwhile and deserving as other people.',
        'I am more self-blaming than usual.',
        'I largely believe that I cause problems for others.',
        'I think almost constantly about major and minor defects in myself.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR12',
      text: 'Thoughts of Death or Suicide?',
      options: [
        'I do not think of suicide or death.',
        'I feel that life is empty or wonder if it’s worth living.',
        'I think of suicide or death several times a week for several minutes.',
        'I think of suicide or death several times a day in some detail, or I have made specific plans for suicide or have actually tried to take my life.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR13',
      text: 'General Interest?',
      options: [
        'There is no change from usual in how interested I am in other people or activities.',
        'I notice that I am less interested in people or activities.',
        'I find I have interest in only one or two of my formerly pursued activities.',
        'I have virtually no interest in formerly pursued activities.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR14',
      text: 'Energy Level?',
      options: [
        'There is no change in my usual level of energy.',
        'I get tired more easily than usual.',
        'I have to make a big effort to start or finish my usual daily activities (for example, shopping, homework, cooking or going to work).',
        'I really cannot carry out most of my usual daily activities because I just don’t have the energy.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR15',
      text: 'Feeling slowed down?',
      options: [
        'I think, speak, and move at my usual rate of speed.',
        'I find that my thinking is slowed down or my voice sounds dull or flat.',
        'It takes me several seconds to respond to most questions and I’m sure my thinking is slowed.',
        'I am often unable to respond to questions without extreme effort.',
      ],
      section: 'Test3',
    },
    {
      id: 'QSR16',
      text: 'Feeling Restless?',
      options: [
        'I do not feel restless.',
        'I’m often fidgety, wringing my hands, or need to shift how I am sitting.',
        'I have impulses to move about and am quite restless.',
        'At times, I am unable to stay seated and need to pace around.',
      ],
      section: 'Test3',
    },
  ];

  
export default questions;  